name: Deploy Terraform

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform init
        run: terraform -chdir=terraform init

      - name: Terraform plan
        run: terraform -chdir=terraform plan -no-color -out=plan.out

      - name: Terraform apply
        run: terraform -chdir=terraform apply -no-color -auto-approve plan.out
